import { LinkedList } from "./modules/linkedList.mjs"

LinkedList.append('node1')
LinkedList.append('node2')
LinkedList.append('TAIL')
LinkedList.prepend('HEAD')
// LinkedList.pop()
// LinkedList.pop()
console.log(LinkedList.HEAD)
// console.log(LinkedList.size())
// console.log(LinkedList.head())
// console.log(LinkedList.tail())
// console.log(LinkedList.at(1))
// console.log(LinkedList.contains('node2'))
// console.log(LinkedList.find('TAIL'))
// console.log(LinkedList.toString())
// console.log(LinkedList.insertAt('new', 0))
console.log(LinkedList.removeAt(1))
console.log(LinkedList.head())